### ISSUE TITLE
Model doesn't load from Hugging Face

### ISSUE THREAD

**Issue by Mcamilo** [MorenoLaQuatra/MATeR#1] opened 2022-06-02 03:53 UTC
Hi Moreno, how are you doing? 

I was not able to load your pre-trained model for advertising classification from HF.

More specifically, I got the following error when trying to import the Tokenizer:

> Can't load tokenizer using from_pretrained, please update its configuration: Can't load tokenizer for 'morenolq/spotify-podcast-advertising-classification'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'morenolq/spotify-podcast-advertising-classification' is the correct path to a directory containing all relevant files for a BertTokenizerFast tokenizer.

And nothing happens when I try to import the model itself. 

If there's another way for me to try out your model I would like that very much.

Thank you, have a good one!

**Comment by MorenoLaQuatra** [comment] 2022-06-02 09:09
Hi Matheus, 

Thank you for pointing out the issue!
I think the problem is that our model relies on a standard `bert-base-cased` tokenizer and we do not redistribute it in the checkpoint repository.
You can load the model using the following snippet:

```python
from transformers import AutoModelForSequenceClassification, AutoTokenizer
model = AutoModelForSequenceClassification.from_pretrained('morenolq/spotify-podcast-advertising-classification')
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')
```
You also find full instructions [here](https://huggingface.co/morenolq/spotify-podcast-advertising-classification)
Let me know if this helps and if you are able to load the model and the tokenizer correctly.

**Comment by MorenoLaQuatra** [comment] 2022-06-09 19:18
We updated the model on the 🤗 Hub including the model's tokenizer and some additional details on the model's classification accuracy.

Now you should be able to both evaluate the model using the 🤗 Hub interface and in your local environment.
I will close this issue for the moment, feel free to re-open if something is not working as expected.

**Closed as completed by MorenoLaQuatra** 2022-06-09 19:18 UTC
